if(EXISTS "/home/me/Projects/CPP/SELF_Resigner_Linux/build-asan/eboot_diff_tests-b12d07c_tests.cmake")
  include("/home/me/Projects/CPP/SELF_Resigner_Linux/build-asan/eboot_diff_tests-b12d07c_tests.cmake")
else()
  add_test(eboot_diff_tests_NOT_BUILT-b12d07c eboot_diff_tests_NOT_BUILT-b12d07c)
endif()
